postgres:
  database: recipes_db_v1
  host: 127.0.0.1
  password: 1111
  port: 5432
  user: postgres
  dialect: postgresql
  driver: psycopg2
server:
  host: 127.0.0.1
  port: 8000
admin_data:
  password: '5556'
  username: admin